# Generated by Django 4.1.1 on 2022-09-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_category_books_active_books_price_books_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
