# Generated by Django 4.1.1 on 2022-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(blank=True, choices=[('availble', 'availble'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
